//pages/sitemap.xml.js
const EXTERNAL_DATA_URL = "https://api-adbacklist.vercel.app/api/blogs";

function generateSiteMap(posts) {
  return `<?xml version="1.0" encoding="UTF-8"?>
   <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
     <!--We manually set the two URLs we know already-->
 
     ${posts

       .map((id) => {
         return `
     <url>
         <loc>${`https://adbacklist.com/blog/${id?.permalink}`}</loc>
     </url>

     `;
       })
       .join("")}
       <url>
       <loc>${`https://adbacklist.com/`}</loc>
      </url>
      <url>
      <loc>https://adbacklist.com/login</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/register</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/user/post</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Auburn</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Birmingham</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Dothan</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Gadsden</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Huntsville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Mobile</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Montgomery</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Muscle%20Shoals</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tuscaloosa</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Anchorage</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fairbanks</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Juneau</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kenai%20Peninsula</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Mohave%20County</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Phoenix</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Prescott</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Show%20Low</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sierra%20Vista</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tucson</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Yuma</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fayetteville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fort%20Smith</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Jonesboro</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Little%20Rock</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bakersfield</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Chico</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fresno</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Humboldt%20County</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Imperial%20County</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Inland%20Empire</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Long%20Beach</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Los%20Angeles</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Mendocino</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Merced</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Modesto</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Monterey</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/North%20Bay</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Orange%20County</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Palm%20Springs</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Palo%20Alto</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Redding</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sacramento</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Diego</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Fernando%20Valley</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Francisco</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Gabriel%20Valley</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Jose</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Luis%20Obispo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Mateo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Santa%20Barbara</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cruz</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Santa%20Maria</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Siskiyou</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Stockton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Susanville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ventura</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Visalia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Boulder</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Colorado%20Springs</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Denver</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fort%20Collins</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Pueblo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Rockies</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Western%20Slope</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bridgeport</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Eastern%20Connecticut</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Hartford</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/New%20Haven</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Northwest%20Connecticut</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Delaware</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Washington%20DC</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Daytona</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fort%20Lauderdale</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fort%20Myers</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Gainesville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Jacksonville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Keys</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lakeland</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Miami</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ocala</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Okaloosa</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Orlando</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Palm%20Bay</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Panama%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Pensacola</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Space%20Coast</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/St.%20Augustine</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tallahassee</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tampa</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Treasure%20Coast</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/West%20Palm%20Beach</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Albany</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Athens</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Atlanta</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Augusta</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brunswick</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Columbus</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Macon</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Northwest%20Georgia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Savannah</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Statesboro</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Valdosta</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Hawaii</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Boise</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/East%20Idaho</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lewiston</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Twin%20Falls</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Carbondale</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Chambana</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Chicago</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Decatur</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/La%20Salle%20County</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Mattoon</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Peoria</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Rockford</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Springfield</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Western%20Illinois</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bloomington</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Evansville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ft%20Wayne</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Indianapolis</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kokomo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lafayette</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Muncie</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Richmond</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/South%20Bend</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Terre%20Haute</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ames</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cedar%20Rapids</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Desmoines</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Dubuque</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fort%20Dodge</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Iowa%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Mason%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Quad%20Cities</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sioux%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Southeast%20Iowa</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Waterloo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lawrence</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Manhattan</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Salina</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Topeka</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Wichita</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bowling%20Green</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Eastern%20Kentucky</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lexington</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Louisville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Owensboro</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Western%20Kentucky</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Alexandria</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Baton%20Rouge</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Houma</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lake%20Charles</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Monroe</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/New%20Orleans</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Shreveport</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Maine</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Annapolis</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Baltimore</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cumberland%20Valley</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Eastern%20Shore</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Frederick</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Western%20Maryland</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Boston</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brockton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cape%20Cod</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lowell</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/South%20Coast</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Worcester</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ann%20Arbor</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Battle%20Creek</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Central%20Michigan</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Detroit</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Flint</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Grand%20Rapids</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Holland</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Jackson</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kalamazoo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lansing</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Muskegon</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Northern%20Michigan</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Port%20Huron</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Saginaw</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Southwest%20Michigan</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Upper%20Peninsula</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bemidji</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brainerd</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Duluth</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Mankato</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Minneapolis</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Rochester</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/St.%20Cloud</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Biloxi</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Hattiesburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Meridian</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/North%20Mississippi</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Southwest%20Mississippi</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Columbia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Joplin</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kansas%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kirksville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lake%20Of%20The%20Ozarks</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Southeast%20Missouri</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/St%20Joseph</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/St.%20Louis</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Billings</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bozeman</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Butte</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Great%20Falls</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Helena</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kalispell</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Missoula</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Grand%20Island</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lincoln</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/North%20Platte</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Omaha</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Scottsbluff</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Elko</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Las%20Vegas</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Reno</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/New%20Hampshire</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Central%20Jersey</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Jersey%20Shore</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lakewood</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/North%20Jersey</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/South%20Jersey</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Albuquerque</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Clovis</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Farmington</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Las%20Cruces</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Roswell</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Santa%20Fe</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Binghamton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bronx</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brooklyn</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Buffalo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Catskills</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Chautauqua</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Elmira</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fairfield</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Finger%20Lakes</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Glens%20Falls</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Hudson%20Valley</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ithaca</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Long%20Island</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/New%20York</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Oneonta</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Plattsburgh</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Potsdam</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Queens</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Staten%20Island</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Syracuse</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Twin%20Tiers</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Utica</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Watertown</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Westchester</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Asheville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Boone</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Charlotte</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Eastern</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Greensboro</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Hickory</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/High%20Point</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Outer%20Banks</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Raleigh-Durham</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Wilmington</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Winston</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bismarck</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fargo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Grand%20Forks</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Minot</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Akron-Canton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ashtabula</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Chillicothe</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cincinnati</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cleveland</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Dayton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Huntington</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lima-Findlay</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Mansfield</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sandusky</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Toledo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tuscarawas%20County</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Youngstown</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cambridge</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lawton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Norman</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Oklahoma%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Stillwater</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tulsa</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bend</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Corvallis</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/East%20Oregon</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Eugene</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Klamath%20Falls</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Medford</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Oregon%20Coast</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Portland</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Roseburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Salem</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Allentown</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Altoona</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Chambersburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Erie</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Harrisburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lancaster</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Meadville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Penn%20State</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Philadelphia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Pittsburgh</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Poconos</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Reading</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Scranton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Williamsport</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/York</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Providence</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Charleston</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Florence</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Greenville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Hilton%20Head</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Myrtle%20Beach</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Aberdeen</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Pierre</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Rapid%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sioux%20Falls</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Chattanooga</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Clarksville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cookeville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Johnson%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Knoxville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Memphis</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Nashville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tri-Cities</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Abilene</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Amarillo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Austin</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Beaumont</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brownsville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/College%20Station</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Corpus%20Christi</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Dallas</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Del%20Rio</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Denton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/El%20Paso</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fort%20Worth</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Galveston</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Houston</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Killeen</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Laredo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lubbock</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Mcallen</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Odessa</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Antonio</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/San%20Marcos</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Texarkana</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Texoma</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tyler</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Victoria</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Waco</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Wichita%20Falls</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Logan</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ogden</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Provo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Salt%20Lake%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/St.%20George</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Vermont</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Charlottesville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Danville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fredericksburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Harrisonburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lynchburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/New%20River%20Valley</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Roanoke</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Southwest%20Virginia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Virginia%20Beach</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bellingham</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Moses%20Lake</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Olympia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Pullman</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Seattle</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Spokane</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tacoma</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Wenatchee</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Yakima</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Morgantown</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Parkersburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Southern%20West%20Virginia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Wheeling</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Appleton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Eau%20Claire</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Green%20Bay</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Janesville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/La%20Crosse</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Madison</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Milwaukee</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Racine</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sheboygan</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Wausau</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Wyoming</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Calgary</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Edmonton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ft%20Mcmurray</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Grande%20Prairie</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lethbridge</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Medicine%20Hat</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Red%20Deer</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/St.%20Albert</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Abbotsford</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cariboo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Comox%20Valley</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cranbrook</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kamloops</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kelowna</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Nanaimo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Peace%20River</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Prince%20George</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Skeena</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sunshine%20Coast</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Vancouver</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Whistler</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brandon</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Winnipeg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Fredericton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Moncton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/St.%20John</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Newfoundland</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Labrador</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Northwest</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Territories</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Nova%20Scotia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Barrie</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Belleville</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brantford</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Chatham</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Cornwall</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Guelph</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Hamilton</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kingston</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kitchener</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/London</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Niagara</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ottawa</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Owen%20Sound</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Peterborough</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sarnia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sault%20Ste%20Marie</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sudbury</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Thunder%20Bay</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Toronto</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Windsor</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Montreal</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Quebec%20City</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Saguenay</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sherbrooke</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Trois-Rivieres</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Prince%20Albert</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Regina</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Saskatoon</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Yukon</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tirane</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Graz</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Innsbruck</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Linz</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Salzburg</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Wien</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Minsk</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Antwerp</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bruges</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brussel</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Charleroi</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ghent</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Liege</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Namur</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Sarajevo</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Balgariya</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Zagreb</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Limassol</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Nicosia</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Brno</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ceske-Budeovice</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Liberec</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Olomouc</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Ostrava</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Plzen</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Praha</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Aarhus</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Kobenhavn</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Tallinn</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Helsinki</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bordeaux</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Bretagne</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Corse</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Departements-Doutre-Mer</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Grenoble</loc>
    </url>
    <url>
      <loc>https://adbacklist.com/Lille</loc>
    </url>

   </urlset>
 `;
}

function SiteMap() {
  // getServerSideProps will do the heavy lifting
}

export async function getServerSideProps({ res }) {
  const request = await fetch(EXTERNAL_DATA_URL);

  const posts = await request.json();

  const news = posts.data.blogs;

  // We generate the XML sitemap with the posts data
  const sitemap = generateSiteMap(news);

  res.setHeader("Content-Type", "text/xml");
  // we send the XML to the browser
  res.write(sitemap);
  res.end();

  return {
    props: {},
  };
}

export default SiteMap;
